/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* cells_not_processed =  1  *)
(* src = "cmos_cells_delay.v:1" *)
module BUF(A, Y);
  (* src = "cmos_cells_delay.v:2" *)
  input A;
  (* src = "cmos_cells_delay.v:3" *)
  output Y;
  assign Y = A;
endmodule

(* cells_not_processed =  1  *)
(* src = "cmos_cells_delay.v:25" *)
module DFF(D, C, Q);
  (* src = "cmos_cells_delay.v:27" *)
  input C;
  (* src = "cmos_cells_delay.v:26" *)
  input D;
  (* src = "cmos_cells_delay.v:28" *)
  output Q;
  (* src = "cmos_cells_delay.v:29" *)
  DFF _0_ (
    .C(C),
    .D(D),
    .Q(Q)
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "cmos_cells_delay.v:13" *)
module NAND(A, B, Y);
  (* src = "cmos_cells_delay.v:14" *)
  wire _0_;
  (* src = "cmos_cells_delay.v:14" *)
  wire _1_;
  (* src = "cmos_cells_delay.v:15" *)
  wire _2_;
  (* src = "cmos_cells_delay.v:16" *)
  wire _3_;
  (* src = "cmos_cells_delay.v:14" *)
  input A;
  (* src = "cmos_cells_delay.v:14" *)
  input B;
  (* src = "cmos_cells_delay.v:15" *)
  output Y;
  NAND _4_ (
    .A(_0_),
    .B(_1_),
    .Y(_2_)
  );
  assign Y = _2_;
  assign _0_ = A;
  assign _1_ = B;
endmodule

(* cells_not_processed =  1  *)
(* src = "cmos_cells_delay.v:19" *)
module NOR(A, B, Y);
  (* src = "cmos_cells_delay.v:20" *)
  wire _0_;
  (* src = "cmos_cells_delay.v:20" *)
  wire _1_;
  (* src = "cmos_cells_delay.v:21" *)
  wire _2_;
  (* src = "cmos_cells_delay.v:22" *)
  wire _3_;
  (* src = "cmos_cells_delay.v:20" *)
  input A;
  (* src = "cmos_cells_delay.v:20" *)
  input B;
  (* src = "cmos_cells_delay.v:21" *)
  output Y;
  NOR _4_ (
    .A(_0_),
    .B(_1_),
    .Y(_2_)
  );
  assign Y = _2_;
  assign _0_ = A;
  assign _1_ = B;
endmodule

(* cells_not_processed =  1  *)
(* src = "cmos_cells_delay.v:7" *)
module NOT(A, Y);
  (* src = "cmos_cells_delay.v:8" *)
  wire _0_;
  (* src = "cmos_cells_delay.v:9" *)
  wire _1_;
  (* src = "cmos_cells_delay.v:8" *)
  input A;
  (* src = "cmos_cells_delay.v:9" *)
  output Y;
  NOT _2_ (
    .A(_0_),
    .Y(_1_)
  );
  assign _0_ = A;
  assign Y = _1_;
endmodule

(* cells_not_processed =  1  *)
(* src = "calculadora.v:2" *)
module calculadora(clk, rst, a, b, MODO, c, rco);
  (* src = "calculadora.v:15" *)
  wire [3:0] _000_;
  (* src = "calculadora.v:15" *)
  wire _001_;
  (* src = "calculadora.v:15" *)
  wire _002_;
  (* src = "calculadora.v:15" *)
  wire _003_;
  (* src = "calculadora.v:15" *)
  wire _004_;
  (* src = "calculadora.v:15" *)
  wire _005_;
  (* src = "calculadora.v:15" *)
  wire _006_;
  (* src = "calculadora.v:7" *)
  wire _007_;
  (* src = "calculadora.v:7" *)
  wire _008_;
  (* src = "calculadora.v:5" *)
  wire _009_;
  (* src = "calculadora.v:5" *)
  wire _010_;
  (* src = "calculadora.v:5" *)
  wire _011_;
  (* src = "calculadora.v:5" *)
  wire _012_;
  (* src = "calculadora.v:6" *)
  wire _013_;
  (* src = "calculadora.v:6" *)
  wire _014_;
  (* src = "calculadora.v:6" *)
  wire _015_;
  (* src = "calculadora.v:6" *)
  wire _016_;
  (* src = "calculadora.v:8" *)
  wire _017_;
  (* src = "calculadora.v:8" *)
  wire _018_;
  (* src = "calculadora.v:8" *)
  wire _019_;
  (* src = "calculadora.v:8" *)
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  (* src = "calculadora.v:9" *)
  wire _204_;
  (* src = "calculadora.v:4" *)
  wire _205_;
  (* src = "calculadora.v:17" *)
  wire [4:0] _206_;
  wire [4:0] _207_;
  wire [4:0] _208_;
  (* unused_bits = "4" *)
  wire [4:0] _209_;
  (* unused_bits = "4" *)
  wire [4:0] _210_;
  (* src = "<techmap.v>:187" *)
  wire [4:0] _211_;
  (* src = "<techmap.v>:187" *)
  (* unused_bits = "4" *)
  wire [4:0] _212_;
  (* src = "<techmap.v>:187" *)
  wire [4:0] _213_;
  (* src = "<techmap.v>:187" *)
  wire [4:0] _214_;
  (* src = "<techmap.v>:187" *)
  (* unused_bits = "4" *)
  wire [4:0] _215_;
  (* src = "<techmap.v>:187" *)
  (* unused_bits = "4" *)
  wire [4:0] _216_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "4" *)
  wire [4:0] _217_;
  wire [4:0] _218_;
  wire [4:0] _219_;
  wire [4:0] _220_;
  wire [4:0] _221_;
  wire [4:0] _222_;
  wire [4:0] _223_;
  wire _224_;
  wire [1:0] _225_;
  wire [1:0] _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire [3:0] _234_;
  wire [3:0] _235_;
  wire [3:0] _236_;
  wire [3:0] _237_;
  (* src = "calculadora.v:18" *)
  wire [4:0] _238_;
  (* src = "calculadora.v:17|<techmap.v>:260|<techmap.v>:203" *)
  wire [4:0] _239_;
  wire [4:0] _240_;
  (* src = "<techmap.v>:260" *)
  (* unused_bits = "4" *)
  wire [4:0] _241_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _242_;
  (* src = "calculadora.v:18|<techmap.v>:258" *)
  wire [4:0] _243_;
  (* src = "calculadora.v:18|<techmap.v>:260|<techmap.v>:203" *)
  wire [4:0] _244_;
  (* src = "calculadora.v:18|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3 4" *)
  wire [4:0] _245_;
  wire [4:0] _246_;
  (* src = "calculadora.v:17|<techmap.v>:260" *)
  wire [4:0] _247_;
  (* src = "calculadora.v:17|<techmap.v>:260|<techmap.v>:221" *)
  wire _248_;
  (* src = "calculadora.v:17|<techmap.v>:260|<techmap.v>:221" *)
  wire _249_;
  (* src = "calculadora.v:17|<techmap.v>:260|<techmap.v>:221" *)
  wire _250_;
  (* src = "calculadora.v:17|<techmap.v>:260|<techmap.v>:222" *)
  wire _251_;
  (* src = "calculadora.v:17|<techmap.v>:260|<techmap.v>:229" *)
  wire _252_;
  (* src = "calculadora.v:17|<techmap.v>:260|<techmap.v>:221" *)
  wire _253_;
  (* src = "calculadora.v:18|<techmap.v>:260" *)
  wire [4:0] _254_;
  (* src = "calculadora.v:18|<techmap.v>:260|<techmap.v>:221" *)
  wire _255_;
  (* src = "calculadora.v:18|<techmap.v>:260|<techmap.v>:221" *)
  wire _256_;
  (* src = "calculadora.v:18|<techmap.v>:260|<techmap.v>:221" *)
  wire _257_;
  (* src = "calculadora.v:18|<techmap.v>:260|<techmap.v>:222" *)
  wire _258_;
  (* src = "calculadora.v:18|<techmap.v>:260|<techmap.v>:229" *)
  wire _259_;
  (* src = "calculadora.v:18|<techmap.v>:260|<techmap.v>:221" *)
  wire _260_;
  (* src = "calculadora.v:7" *)
  input [1:0] MODO;
  (* src = "calculadora.v:5" *)
  input [3:0] a;
  (* src = "calculadora.v:6" *)
  input [3:0] b;
  (* src = "calculadora.v:8" *)
  output [3:0] c;
  (* src = "calculadora.v:3" *)
  input clk;
  (* src = "calculadora.v:9" *)
  output rco;
  (* src = "calculadora.v:4" *)
  input rst;
  NOT _261_ (
    .A(_007_),
    .Y(_126_)
  );
  NOT _262_ (
    .A(_008_),
    .Y(_127_)
  );
  NOT _263_ (
    .A(_012_),
    .Y(_128_)
  );
  NOT _264_ (
    .A(_205_),
    .Y(_129_)
  );
  NOT _265_ (
    .A(_009_),
    .Y(_130_)
  );
  NOT _266_ (
    .A(_010_),
    .Y(_131_)
  );
  NOT _267_ (
    .A(_011_),
    .Y(_132_)
  );
  NOT _268_ (
    .A(_015_),
    .Y(_133_)
  );
  NOT _269_ (
    .A(_013_),
    .Y(_134_)
  );
  NOT _270_ (
    .A(_014_),
    .Y(_135_)
  );
  NOT _271_ (
    .A(_016_),
    .Y(_136_)
  );
  NAND _272_ (
    .A(_012_),
    .B(_016_),
    .Y(_137_)
  );
  NOR _273_ (
    .A(_012_),
    .B(_136_),
    .Y(_138_)
  );
  NAND _274_ (
    .A(_128_),
    .B(_016_),
    .Y(_139_)
  );
  NAND _275_ (
    .A(_012_),
    .B(_136_),
    .Y(_140_)
  );
  NAND _276_ (
    .A(_139_),
    .B(_140_),
    .Y(_141_)
  );
  NOR _277_ (
    .A(_132_),
    .B(_133_),
    .Y(_142_)
  );
  NAND _278_ (
    .A(_011_),
    .B(_015_),
    .Y(_143_)
  );
  NOR _279_ (
    .A(_011_),
    .B(_133_),
    .Y(_144_)
  );
  NOR _280_ (
    .A(_132_),
    .B(_015_),
    .Y(_145_)
  );
  NOR _281_ (
    .A(_144_),
    .B(_145_),
    .Y(_146_)
  );
  NOT _282_ (
    .A(_146_),
    .Y(_147_)
  );
  NAND _283_ (
    .A(_010_),
    .B(_014_),
    .Y(_148_)
  );
  NOT _284_ (
    .A(_148_),
    .Y(_149_)
  );
  NAND _285_ (
    .A(_131_),
    .B(_014_),
    .Y(_150_)
  );
  NAND _286_ (
    .A(_010_),
    .B(_135_),
    .Y(_151_)
  );
  NAND _287_ (
    .A(_150_),
    .B(_151_),
    .Y(_152_)
  );
  NOR _288_ (
    .A(_130_),
    .B(_134_),
    .Y(_153_)
  );
  NAND _289_ (
    .A(_009_),
    .B(_013_),
    .Y(_154_)
  );
  NAND _290_ (
    .A(_152_),
    .B(_153_),
    .Y(_155_)
  );
  NAND _291_ (
    .A(_148_),
    .B(_155_),
    .Y(_156_)
  );
  NAND _292_ (
    .A(_147_),
    .B(_156_),
    .Y(_157_)
  );
  NAND _293_ (
    .A(_143_),
    .B(_157_),
    .Y(_158_)
  );
  NAND _294_ (
    .A(_141_),
    .B(_158_),
    .Y(_159_)
  );
  NAND _295_ (
    .A(_137_),
    .B(_159_),
    .Y(_160_)
  );
  NOR _296_ (
    .A(_007_),
    .B(_008_),
    .Y(_161_)
  );
  NOT _297_ (
    .A(_161_),
    .Y(_162_)
  );
  NAND _298_ (
    .A(_160_),
    .B(_161_),
    .Y(_163_)
  );
  NOT _299_ (
    .A(_163_),
    .Y(_164_)
  );
  NAND _300_ (
    .A(_009_),
    .B(_015_),
    .Y(_165_)
  );
  NOT _301_ (
    .A(_165_),
    .Y(_166_)
  );
  NAND _302_ (
    .A(_011_),
    .B(_013_),
    .Y(_167_)
  );
  NOR _303_ (
    .A(_143_),
    .B(_154_),
    .Y(_168_)
  );
  NAND _304_ (
    .A(_142_),
    .B(_153_),
    .Y(_169_)
  );
  NAND _305_ (
    .A(_012_),
    .B(_013_),
    .Y(_170_)
  );
  NOT _306_ (
    .A(_170_),
    .Y(_171_)
  );
  NAND _307_ (
    .A(_010_),
    .B(_015_),
    .Y(_172_)
  );
  NAND _308_ (
    .A(_009_),
    .B(_016_),
    .Y(_173_)
  );
  NOR _309_ (
    .A(_131_),
    .B(_136_),
    .Y(_174_)
  );
  NAND _310_ (
    .A(_010_),
    .B(_016_),
    .Y(_175_)
  );
  NOR _311_ (
    .A(_165_),
    .B(_175_),
    .Y(_176_)
  );
  NAND _312_ (
    .A(_166_),
    .B(_174_),
    .Y(_177_)
  );
  NAND _313_ (
    .A(_172_),
    .B(_173_),
    .Y(_178_)
  );
  NOT _314_ (
    .A(_178_),
    .Y(_179_)
  );
  NOR _315_ (
    .A(_176_),
    .B(_179_),
    .Y(_180_)
  );
  NAND _316_ (
    .A(_177_),
    .B(_178_),
    .Y(_181_)
  );
  NOR _317_ (
    .A(_170_),
    .B(_181_),
    .Y(_182_)
  );
  NAND _318_ (
    .A(_171_),
    .B(_180_),
    .Y(_183_)
  );
  NOR _319_ (
    .A(_171_),
    .B(_180_),
    .Y(_184_)
  );
  NAND _320_ (
    .A(_170_),
    .B(_181_),
    .Y(_185_)
  );
  NOR _321_ (
    .A(_182_),
    .B(_184_),
    .Y(_186_)
  );
  NAND _322_ (
    .A(_183_),
    .B(_185_),
    .Y(_187_)
  );
  NOR _323_ (
    .A(_169_),
    .B(_187_),
    .Y(_188_)
  );
  NAND _324_ (
    .A(_168_),
    .B(_186_),
    .Y(_189_)
  );
  NAND _325_ (
    .A(_011_),
    .B(_014_),
    .Y(_190_)
  );
  NOT _326_ (
    .A(_190_),
    .Y(_191_)
  );
  NOR _327_ (
    .A(_168_),
    .B(_186_),
    .Y(_192_)
  );
  NAND _328_ (
    .A(_169_),
    .B(_187_),
    .Y(_193_)
  );
  NOR _329_ (
    .A(_188_),
    .B(_192_),
    .Y(_194_)
  );
  NAND _330_ (
    .A(_189_),
    .B(_193_),
    .Y(_195_)
  );
  NOR _331_ (
    .A(_190_),
    .B(_195_),
    .Y(_196_)
  );
  NAND _332_ (
    .A(_191_),
    .B(_194_),
    .Y(_197_)
  );
  NOR _333_ (
    .A(_188_),
    .B(_196_),
    .Y(_198_)
  );
  NAND _334_ (
    .A(_189_),
    .B(_197_),
    .Y(_199_)
  );
  NOR _335_ (
    .A(_176_),
    .B(_182_),
    .Y(_200_)
  );
  NAND _336_ (
    .A(_177_),
    .B(_183_),
    .Y(_201_)
  );
  NAND _337_ (
    .A(_012_),
    .B(_014_),
    .Y(_202_)
  );
  NOT _338_ (
    .A(_202_),
    .Y(_203_)
  );
  NOR _339_ (
    .A(_142_),
    .B(_175_),
    .Y(_021_)
  );
  NAND _340_ (
    .A(_143_),
    .B(_174_),
    .Y(_022_)
  );
  NOR _341_ (
    .A(_143_),
    .B(_174_),
    .Y(_023_)
  );
  NAND _342_ (
    .A(_142_),
    .B(_175_),
    .Y(_024_)
  );
  NOR _343_ (
    .A(_021_),
    .B(_023_),
    .Y(_025_)
  );
  NAND _344_ (
    .A(_022_),
    .B(_024_),
    .Y(_026_)
  );
  NOR _345_ (
    .A(_202_),
    .B(_026_),
    .Y(_027_)
  );
  NAND _346_ (
    .A(_203_),
    .B(_025_),
    .Y(_028_)
  );
  NOR _347_ (
    .A(_203_),
    .B(_025_),
    .Y(_029_)
  );
  NAND _348_ (
    .A(_202_),
    .B(_026_),
    .Y(_030_)
  );
  NOR _349_ (
    .A(_027_),
    .B(_029_),
    .Y(_031_)
  );
  NAND _350_ (
    .A(_028_),
    .B(_030_),
    .Y(_032_)
  );
  NOR _351_ (
    .A(_200_),
    .B(_032_),
    .Y(_033_)
  );
  NAND _352_ (
    .A(_201_),
    .B(_031_),
    .Y(_034_)
  );
  NOR _353_ (
    .A(_201_),
    .B(_031_),
    .Y(_035_)
  );
  NAND _354_ (
    .A(_200_),
    .B(_032_),
    .Y(_036_)
  );
  NOR _355_ (
    .A(_033_),
    .B(_035_),
    .Y(_037_)
  );
  NAND _356_ (
    .A(_034_),
    .B(_036_),
    .Y(_038_)
  );
  NOR _357_ (
    .A(_199_),
    .B(_037_),
    .Y(_039_)
  );
  NOR _358_ (
    .A(_198_),
    .B(_038_),
    .Y(_040_)
  );
  NOR _359_ (
    .A(_039_),
    .B(_040_),
    .Y(_041_)
  );
  NOR _360_ (
    .A(_007_),
    .B(_127_),
    .Y(_042_)
  );
  NOT _361_ (
    .A(_042_),
    .Y(_043_)
  );
  NOR _362_ (
    .A(_191_),
    .B(_194_),
    .Y(_044_)
  );
  NOR _363_ (
    .A(_196_),
    .B(_044_),
    .Y(_045_)
  );
  NAND _364_ (
    .A(_165_),
    .B(_167_),
    .Y(_046_)
  );
  NAND _365_ (
    .A(_169_),
    .B(_046_),
    .Y(_047_)
  );
  NAND _366_ (
    .A(_009_),
    .B(_014_),
    .Y(_048_)
  );
  NAND _367_ (
    .A(_010_),
    .B(_013_),
    .Y(_049_)
  );
  NOR _368_ (
    .A(_148_),
    .B(_154_),
    .Y(_050_)
  );
  NOR _369_ (
    .A(_153_),
    .B(_046_),
    .Y(_051_)
  );
  NOR _370_ (
    .A(_148_),
    .B(_051_),
    .Y(_052_)
  );
  NAND _371_ (
    .A(_045_),
    .B(_052_),
    .Y(_053_)
  );
  NAND _372_ (
    .A(_042_),
    .B(_053_),
    .Y(_054_)
  );
  NOR _373_ (
    .A(_041_),
    .B(_054_),
    .Y(_055_)
  );
  NOR _374_ (
    .A(_126_),
    .B(_128_),
    .Y(_056_)
  );
  NAND _375_ (
    .A(_127_),
    .B(_204_),
    .Y(_057_)
  );
  NOR _376_ (
    .A(_126_),
    .B(_008_),
    .Y(_058_)
  );
  NAND _377_ (
    .A(_007_),
    .B(_127_),
    .Y(_059_)
  );
  NAND _378_ (
    .A(_057_),
    .B(_059_),
    .Y(_060_)
  );
  NOR _379_ (
    .A(_056_),
    .B(_060_),
    .Y(_061_)
  );
  NOR _380_ (
    .A(_043_),
    .B(_053_),
    .Y(_062_)
  );
  NAND _381_ (
    .A(_041_),
    .B(_062_),
    .Y(_063_)
  );
  NAND _382_ (
    .A(_061_),
    .B(_063_),
    .Y(_064_)
  );
  NOR _383_ (
    .A(_055_),
    .B(_064_),
    .Y(_065_)
  );
  NOR _384_ (
    .A(_009_),
    .B(_013_),
    .Y(_066_)
  );
  NOR _385_ (
    .A(_153_),
    .B(_066_),
    .Y(_067_)
  );
  NOR _386_ (
    .A(_009_),
    .B(_134_),
    .Y(_068_)
  );
  NOR _387_ (
    .A(_152_),
    .B(_068_),
    .Y(_069_)
  );
  NOT _388_ (
    .A(_069_),
    .Y(_070_)
  );
  NAND _389_ (
    .A(_151_),
    .B(_070_),
    .Y(_071_)
  );
  NAND _390_ (
    .A(_146_),
    .B(_071_),
    .Y(_072_)
  );
  NOT _391_ (
    .A(_072_),
    .Y(_073_)
  );
  NOR _392_ (
    .A(_145_),
    .B(_073_),
    .Y(_074_)
  );
  NAND _393_ (
    .A(_140_),
    .B(_074_),
    .Y(_075_)
  );
  NOR _394_ (
    .A(_008_),
    .B(_138_),
    .Y(_076_)
  );
  NAND _395_ (
    .A(_075_),
    .B(_076_),
    .Y(_077_)
  );
  NAND _396_ (
    .A(_162_),
    .B(_077_),
    .Y(_078_)
  );
  NOR _397_ (
    .A(_065_),
    .B(_078_),
    .Y(_079_)
  );
  NOR _398_ (
    .A(_164_),
    .B(_079_),
    .Y(_080_)
  );
  NOR _399_ (
    .A(_205_),
    .B(_080_),
    .Y(_006_)
  );
  NOR _400_ (
    .A(_042_),
    .B(_067_),
    .Y(_081_)
  );
  NAND _401_ (
    .A(_008_),
    .B(_154_),
    .Y(_082_)
  );
  NAND _402_ (
    .A(_129_),
    .B(_082_),
    .Y(_083_)
  );
  NOR _403_ (
    .A(_081_),
    .B(_083_),
    .Y(_002_)
  );
  NAND _404_ (
    .A(_152_),
    .B(_068_),
    .Y(_084_)
  );
  NOR _405_ (
    .A(_059_),
    .B(_069_),
    .Y(_085_)
  );
  NAND _406_ (
    .A(_084_),
    .B(_085_),
    .Y(_086_)
  );
  NOR _407_ (
    .A(_152_),
    .B(_153_),
    .Y(_087_)
  );
  NAND _408_ (
    .A(_155_),
    .B(_161_),
    .Y(_088_)
  );
  NOR _409_ (
    .A(_087_),
    .B(_088_),
    .Y(_089_)
  );
  NAND _410_ (
    .A(_007_),
    .B(_008_),
    .Y(_090_)
  );
  NOR _411_ (
    .A(_130_),
    .B(_090_),
    .Y(_091_)
  );
  NAND _412_ (
    .A(_048_),
    .B(_049_),
    .Y(_092_)
  );
  NAND _413_ (
    .A(_042_),
    .B(_092_),
    .Y(_093_)
  );
  NOR _414_ (
    .A(_050_),
    .B(_093_),
    .Y(_094_)
  );
  NOR _415_ (
    .A(_091_),
    .B(_094_),
    .Y(_095_)
  );
  NAND _416_ (
    .A(_086_),
    .B(_095_),
    .Y(_096_)
  );
  NOR _417_ (
    .A(_089_),
    .B(_096_),
    .Y(_097_)
  );
  NOR _418_ (
    .A(_205_),
    .B(_097_),
    .Y(_003_)
  );
  NOR _419_ (
    .A(_146_),
    .B(_071_),
    .Y(_098_)
  );
  NAND _420_ (
    .A(_058_),
    .B(_072_),
    .Y(_099_)
  );
  NOR _421_ (
    .A(_098_),
    .B(_099_),
    .Y(_100_)
  );
  NOR _422_ (
    .A(_147_),
    .B(_156_),
    .Y(_101_)
  );
  NOR _423_ (
    .A(_162_),
    .B(_101_),
    .Y(_102_)
  );
  NAND _424_ (
    .A(_157_),
    .B(_102_),
    .Y(_103_)
  );
  NOR _425_ (
    .A(_131_),
    .B(_090_),
    .Y(_104_)
  );
  NAND _426_ (
    .A(_149_),
    .B(_154_),
    .Y(_105_)
  );
  NOR _427_ (
    .A(_047_),
    .B(_105_),
    .Y(_106_)
  );
  NAND _428_ (
    .A(_047_),
    .B(_105_),
    .Y(_107_)
  );
  NAND _429_ (
    .A(_042_),
    .B(_107_),
    .Y(_108_)
  );
  NOR _430_ (
    .A(_106_),
    .B(_108_),
    .Y(_109_)
  );
  NOR _431_ (
    .A(_104_),
    .B(_109_),
    .Y(_110_)
  );
  NAND _432_ (
    .A(_103_),
    .B(_110_),
    .Y(_111_)
  );
  NOR _433_ (
    .A(_100_),
    .B(_111_),
    .Y(_112_)
  );
  NOR _434_ (
    .A(_205_),
    .B(_112_),
    .Y(_004_)
  );
  NOR _435_ (
    .A(_045_),
    .B(_052_),
    .Y(_113_)
  );
  NOR _436_ (
    .A(_054_),
    .B(_113_),
    .Y(_114_)
  );
  NOR _437_ (
    .A(_141_),
    .B(_074_),
    .Y(_115_)
  );
  NAND _438_ (
    .A(_141_),
    .B(_074_),
    .Y(_116_)
  );
  NOR _439_ (
    .A(_059_),
    .B(_115_),
    .Y(_117_)
  );
  NAND _440_ (
    .A(_116_),
    .B(_117_),
    .Y(_118_)
  );
  NOR _441_ (
    .A(_141_),
    .B(_158_),
    .Y(_119_)
  );
  NAND _442_ (
    .A(_159_),
    .B(_161_),
    .Y(_120_)
  );
  NOR _443_ (
    .A(_119_),
    .B(_120_),
    .Y(_121_)
  );
  NOR _444_ (
    .A(_132_),
    .B(_090_),
    .Y(_122_)
  );
  NOR _445_ (
    .A(_121_),
    .B(_122_),
    .Y(_123_)
  );
  NAND _446_ (
    .A(_118_),
    .B(_123_),
    .Y(_124_)
  );
  NOR _447_ (
    .A(_114_),
    .B(_124_),
    .Y(_125_)
  );
  NOR _448_ (
    .A(_205_),
    .B(_125_),
    .Y(_005_)
  );
  (* src = "calculadora.v:15" *)
  DFF _449_ (
    .C(clk),
    .D(_000_[0]),
    .Q(c[0])
  );
  (* src = "calculadora.v:15" *)
  DFF _450_ (
    .C(clk),
    .D(_000_[1]),
    .Q(c[1])
  );
  (* src = "calculadora.v:15" *)
  DFF _451_ (
    .C(clk),
    .D(_000_[2]),
    .Q(c[2])
  );
  (* src = "calculadora.v:15" *)
  DFF _452_ (
    .C(clk),
    .D(_000_[3]),
    .Q(c[3])
  );
  (* src = "calculadora.v:15" *)
  DFF _453_ (
    .C(clk),
    .D(_001_),
    .Q(rco)
  );
  assign _208_[0] = _207_[0];
  assign _209_[1:0] = 2'h0;
  assign _210_[0] = 1'h0;
  assign { _211_[4], _211_[1:0] } = { _207_[4], 2'h0 };
  assign { _212_[4], _212_[2:0] } = { _209_[4], 3'h0 };
  assign { _213_[4], _213_[2:0] } = { 1'h0, _209_[2], 2'h0 };
  assign _214_[2:0] = _207_[2:0];
  assign _215_[2:0] = 3'h0;
  assign _216_[2:0] = { _210_[2:1], 1'h0 };
  assign _217_[1:0] = 2'h0;
  assign _218_[1:0] = { _208_[1], _207_[0] };
  assign _219_[2:0] = { _218_[2], _208_[1], _207_[0] };
  assign { _220_[4], _220_[1:0] } = { 1'h0, _207_[1:0] };
  assign _221_[0] = 1'h0;
  assign _222_[2:0] = { _211_[2], 2'h0 };
  assign _223_[2:0] = 3'h0;
  assign _225_[0] = MODO[0];
  assign _226_[1] = _225_[1];
  assign { _239_[4:3], _239_[0] } = { 1'h0, _206_[4], _207_[0] };
  assign { _240_[4], _240_[0] } = { 1'h0, _206_[0] };
  assign _241_[2:0] = { _217_[2], 2'h0 };
  assign _243_[4] = 1'h1;
  assign _244_[3] = _244_[4];
  assign { _246_[4], _246_[0] } = { 1'h1, _245_[0] };
  assign { _247_[4], _247_[2:0] } = { 1'h0, _222_[4], _221_[2], _207_[0] };
  assign _254_[4] = 1'h0;
  assign _007_ = MODO[0];
  assign _008_ = MODO[1];
  assign _012_ = a[3];
  assign _204_ = rco;
  assign _205_ = rst;
  assign _001_ = _006_;
  assign _017_ = c[0];
  assign _009_ = a[0];
  assign _018_ = c[1];
  assign _010_ = a[1];
  assign _019_ = c[2];
  assign _011_ = a[2];
  assign _020_ = c[3];
  assign _000_[0] = _002_;
  assign _000_[1] = _003_;
  assign _000_[2] = _004_;
  assign _000_[3] = _005_;
  assign _015_ = b[2];
  assign _013_ = b[0];
  assign _014_ = b[1];
  assign _016_ = b[3];
endmodule
