/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* cells_not_processed =  1  *)
(* src = "cmos_cells_delay.v:1.1-5.10" *)
module BUF(A, Y);
  (* src = "cmos_cells_delay.v:2.9-2.10" *)
  input A;
  wire A;
  (* src = "cmos_cells_delay.v:3.10-3.11" *)
  output Y;
  wire Y;
  assign Y = A;
endmodule

(* cells_not_processed =  1  *)
(* src = "cmos_cells_delay.v:25.1-30.10" *)
module DFF(D, C, Q);
  (* src = "cmos_cells_delay.v:27.9-27.10" *)
  input C;
  wire C;
  (* src = "cmos_cells_delay.v:26.9-26.10" *)
  input D;
  wire D;
  (* src = "cmos_cells_delay.v:28.14-28.15" *)
  output Q;
  wire Q;
  (* src = "cmos_cells_delay.v:29.3-29.30" *)
  DFF _0_ (
    .C(C),
    .D(D),
    .Q(Q)
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "cmos_cells_delay.v:13.1-17.10" *)
module NAND(A, B, Y);
  (* src = "cmos_cells_delay.v:14.9-14.10" *)
  input A;
  wire A;
  (* src = "cmos_cells_delay.v:14.12-14.13" *)
  input B;
  wire B;
  (* src = "cmos_cells_delay.v:15.10-15.11" *)
  output Y;
  wire Y;
  NAND _0_ (
    .A(A),
    .B(B),
    .Y(Y)
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "cmos_cells_delay.v:19.1-23.10" *)
module NOR(A, B, Y);
  (* src = "cmos_cells_delay.v:20.9-20.10" *)
  input A;
  wire A;
  (* src = "cmos_cells_delay.v:20.12-20.13" *)
  input B;
  wire B;
  (* src = "cmos_cells_delay.v:21.10-21.11" *)
  output Y;
  wire Y;
  NOR _0_ (
    .A(A),
    .B(B),
    .Y(Y)
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "cmos_cells_delay.v:7.1-11.10" *)
module NOT(A, Y);
  (* src = "cmos_cells_delay.v:8.9-8.10" *)
  input A;
  wire A;
  (* src = "cmos_cells_delay.v:9.10-9.11" *)
  output Y;
  wire Y;
  NOT _0_ (
    .A(A),
    .Y(Y)
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "lavadora.v:2.1-98.10" *)
module lavadora(clk, rst, INTRO_MONEDA, FINALIZAR_PAGO, INSUFCIENTE, SECADO, LAVADO, LAVADO_PESADO, VERIFICACION);
  (* src = "lavadora.v:5.31-5.45" *)
  input FINALIZAR_PAGO;
  wire FINALIZAR_PAGO;
  (* src = "lavadora.v:6.12-6.23" *)
  output INSUFCIENTE;
  wire INSUFCIENTE;
  (* src = "lavadora.v:5.17-5.29" *)
  input INTRO_MONEDA;
  wire INTRO_MONEDA;
  (* src = "lavadora.v:6.33-6.39" *)
  output LAVADO;
  wire LAVADO;
  (* src = "lavadora.v:6.41-6.54" *)
  output LAVADO_PESADO;
  wire LAVADO_PESADO;
  (* src = "lavadora.v:6.25-6.31" *)
  output SECADO;
  wire SECADO;
  (* src = "lavadora.v:6.56-6.68" *)
  output VERIFICACION;
  wire VERIFICACION;
  (* src = "lavadora.v:5.7-5.10" *)
  input clk;
  wire clk;
  (* src = "lavadora.v:5.12-5.15" *)
  input rst;
  wire rst;
  assign INSUFCIENTE = 1'h0;
  assign LAVADO = 1'h0;
  assign LAVADO_PESADO = 1'h0;
  assign SECADO = 1'h0;
  assign VERIFICACION = 1'h0;
endmodule
